INSERT INTO trainer (firstName, lastName, userName, password, isActive, specialization, specialization_fk) VALUES
                                                                                                               ('John', 'Doe', 'John.Doe', 'pass123', true, 'STRENGTH', 1),
                                                                                                               ('Jane', 'Smith', 'Jane.Smith', 'pass456', true, 'YOGA', 3),
                                                                                                               ('Michael', 'Scott', 'Michael.Scott', 'michael123', true, 'STRENGTH', 1),
                                                                                                               ('Dwight', 'Schrute', 'Dwight.Schrute', 'dwight123', true, 'CROSSFIT', 4),
                                                                                                               ('Ryan', 'Howard', 'Ryan.Howard', 'ryan123', true, 'CROSSFIT', 4),
                                                                                                               ('Kelly', 'Kapoor', 'Kelly.Kapoor', 'kelly123', true, 'CARDIO', 2),
                                                                                                               ('Angela', 'Martin', 'Angela.Martin', 'angela123', true, 'YOGA', 3),
                                                                                                               ('Andy', 'Bernard', 'Andy.Bernard', 'andy123', true, 'STRENGTH', 1),
                                                                                                               ('Creed', 'Bratton', 'Creed.Bratton', 'creed123', true, 'PILATES', 5),
                                                                                                               ('Clark', 'Green', 'Clark.Green', 'clark123', true, 'PILATES', 5),
                                                                                                               ('Pete', 'Miller', 'Pete.Miller', 'pete123', true, 'PILATES', 5),
                                                                                                               ('Nellie', 'Bertram', 'Nellie.Bertram', 'nellie123', true, 'YOGA', 3),
                                                                                                               ('Charles', 'Miner', 'Charles.Miner', 'charles123', true, 'CROSSFIT', 4),
                                                                                                               ('Robert', 'California', 'Robert.California', 'robert123', true, 'STRENGTH', 1),
                                                                                                               ('Deangelo', 'Vickers', 'Deangelo.Vickers', 'deangelo123', true, 'CARDIO', 2);